### ISSUE TITLE
ld/configure.tgt uses nds32*le-*-linux-gnu*

### ISSUE THREAD

**Issue by wbx-github** [andestech/binutils#1]
Hi,

is there a reason using gnu suffix? It prevents using binutils for a uClibc-ng toolchain.

best regards
 Waldemar

**Comment by kito-cheng** [comment]
Ooops, it's our mistake during upgrading binutils, I've pushed a commit to fix that https://github.com/andestech/binutils/commit/b7c422667855b1b4b3dc132e58c805787c37b52a .
